package com.milelog.retrofit.response

import com.milelog.retrofit.request.Address

data class GetDrivingInfoResponse (
    val id:String,
    val userId:String,
    val carId:String,
    val userCarId:String,
    val createdAt:String,
    val updatedAt:String,
    val startTime:String,
    val endTime:String,
    val totalTime:Double,
    val totalDistance:Double,
    val maxSpeed:Double,
    val averageSpeed:Double,
    val highSpeedDrivingTime:Double,
    val highSpeedDrivingDistance:Double,
    val highSpeedDrivingMaxSpeed:Double,
    val highSpeedDrivingAverageSpeed:Double,
    val highSpeedDrivingDistancePercentage:Double,
    val highSpeedDrivingTimePercentage:Double,
    val lowSpeedDrivingTime:Double,
    val lowSpeedDrivingDistance:Double,
    val lowSpeedDrivingMaxSpeed:Double,
    val lowSpeedDrivingAverageSpeed:Double,
    val lowSpeedDrivingDistancePercentage:Double,
    val lowSpeedDrivingTimePercentage:Double,
    val etcSpeedDrivingTime:Double,
    val etcSpeedDrivingDistance:Double,
    val etcSpeedDrivingMaxSpeed:Double,
    val etcSpeedDrivingAverageSpeed:Double,
    val etcSpeedDrivingDistancePercentage:Double,
    val etcSpeedDrivingTimePercentage:Double,
    val constantSpeedDrivingTime:Double,
    val constantSpeedDrivingDistance:Double,
    val constantSpeedDrivingMaxSpeed:Double,
    val constantSpeedDrivingAverageSpeed:Double,
    val constantSpeedDrivingDistancePercentage:Double,
    val constantSpeedDrivingTimePercentage:Double,
    val stopTime:Double,
    val stopCount:Double,
    val stopTimePercentage:Double,
    val rapidAccelerationCount:Double,
    val rapidAccelerationDistance:Double,
    val rapidDecelerationCount:Double,
    val rapidDecelerationDistance:Double,
    val rapidStartCount:Double,
    val rapidStartDistance:Double,
    val rapidStopCount:Double,
    val rapidStopDistance:Double,
    val totalRapidCount:Double,
    val optimalDrivingDistance:Double,
    val optimalDrivingPercentage:Double,
    val harshDrivingDistance:Double,
    val harshDrivingPercentage:Double,
    val verification:String,
    val isActive:Boolean,
    val startAddress: Address,
    val endAddress: Address,
    val memo:String
    ) : java.io.Serializable